/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedStoryboardListSimpleRouteImport } from './routes/_authenticated/storyboard-list-simple'
import { Route as AuthenticatedStoryboardListRouteImport } from './routes/_authenticated/storyboard-list'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAssetsRouteRouteImport } from './routes/_authenticated/assets/route'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated/team/index'
import { Route as AuthenticatedStoryboardIndexRouteImport } from './routes/_authenticated/storyboard/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedScriptIndexRouteImport } from './routes/_authenticated/script/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCharacterIndexRouteImport } from './routes/_authenticated/character/index'
import { Route as AuthenticatedSystemTasksRouteImport } from './routes/_authenticated/system/tasks'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsApiDocsRouteImport } from './routes/_authenticated/settings/api-docs'
import { Route as AuthenticatedSettingsApiRouteImport } from './routes/_authenticated/settings/api'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDirectorDirectorRouteRouteImport } from './routes/_authenticated/director/$director/route'
import { Route as AuthenticatedProjectsIdIndexRouteImport } from './routes/_authenticated/projects/$id/index'
import { Route as AuthenticatedProjectsIdTeamRouteImport } from './routes/_authenticated/projects/$id/team'
import { Route as AuthenticatedProjectsIdScriptRouteImport } from './routes/_authenticated/projects/$id/script'
import { Route as AuthenticatedProjectsIdAssetsRouteRouteImport } from './routes/_authenticated/projects/$id/assets/route'
import { Route as AuthenticatedProjectsIdStoryboardIndexRouteImport } from './routes/_authenticated/projects/$id/storyboard/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoryboardListSimpleRoute =
  AuthenticatedStoryboardListSimpleRouteImport.update({
    id: '/storyboard-list-simple',
    path: '/storyboard-list-simple',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStoryboardListRoute =
  AuthenticatedStoryboardListRouteImport.update({
    id: '/storyboard-list',
    path: '/storyboard-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsRouteRoute =
  AuthenticatedAssetsRouteRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTeamRoute,
} as any)
const AuthenticatedStoryboardIndexRoute =
  AuthenticatedStoryboardIndexRouteImport.update({
    id: '/storyboard/',
    path: '/storyboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedScriptIndexRoute =
  AuthenticatedScriptIndexRouteImport.update({
    id: '/script/',
    path: '/script/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCharacterIndexRoute =
  AuthenticatedCharacterIndexRouteImport.update({
    id: '/character/',
    path: '/character/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemTasksRoute =
  AuthenticatedSystemTasksRouteImport.update({
    id: '/system/tasks',
    path: '/system/tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsApiDocsRoute =
  AuthenticatedSettingsApiDocsRouteImport.update({
    id: '/api-docs',
    path: '/api-docs',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsApiRoute =
  AuthenticatedSettingsApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDirectorDirectorRouteRoute =
  AuthenticatedDirectorDirectorRouteRouteImport.update({
    id: '/director/$director',
    path: '/director/$director',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdIndexRoute =
  AuthenticatedProjectsIdIndexRouteImport.update({
    id: '/projects/$id/',
    path: '/projects/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdTeamRoute =
  AuthenticatedProjectsIdTeamRouteImport.update({
    id: '/projects/$id/team',
    path: '/projects/$id/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdScriptRoute =
  AuthenticatedProjectsIdScriptRouteImport.update({
    id: '/projects/$id/script',
    path: '/projects/$id/script',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdAssetsRouteRoute =
  AuthenticatedProjectsIdAssetsRouteRouteImport.update({
    id: '/projects/$id/assets',
    path: '/projects/$id/assets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIdStoryboardIndexRoute =
  AuthenticatedProjectsIdStoryboardIndexRouteImport.update({
    id: '/projects/$id/storyboard/',
    path: '/projects/$id/storyboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/assets': typeof AuthenticatedAssetsRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/storyboard-list': typeof AuthenticatedStoryboardListRoute
  '/storyboard-list-simple': typeof AuthenticatedStoryboardListSimpleRoute
  '/team': typeof AuthenticatedTeamRouteWithChildren
  '/test': typeof AuthenticatedTestRoute
  '/': typeof AuthenticatedIndexRoute
  '/director/$director': typeof AuthenticatedDirectorDirectorRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/settings/api-docs': typeof AuthenticatedSettingsApiDocsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/system/tasks': typeof AuthenticatedSystemTasksRoute
  '/character': typeof AuthenticatedCharacterIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/script': typeof AuthenticatedScriptIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/storyboard': typeof AuthenticatedStoryboardIndexRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
  '/projects/$id/assets': typeof AuthenticatedProjectsIdAssetsRouteRoute
  '/projects/$id/script': typeof AuthenticatedProjectsIdScriptRoute
  '/projects/$id/team': typeof AuthenticatedProjectsIdTeamRoute
  '/projects/$id': typeof AuthenticatedProjectsIdIndexRoute
  '/projects/$id/storyboard': typeof AuthenticatedProjectsIdStoryboardIndexRoute
}
export interface FileRoutesByTo {
  '/assets': typeof AuthenticatedAssetsRouteRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/storyboard-list': typeof AuthenticatedStoryboardListRoute
  '/storyboard-list-simple': typeof AuthenticatedStoryboardListSimpleRoute
  '/test': typeof AuthenticatedTestRoute
  '/': typeof AuthenticatedIndexRoute
  '/director/$director': typeof AuthenticatedDirectorDirectorRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/api': typeof AuthenticatedSettingsApiRoute
  '/settings/api-docs': typeof AuthenticatedSettingsApiDocsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/system/tasks': typeof AuthenticatedSystemTasksRoute
  '/character': typeof AuthenticatedCharacterIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/script': typeof AuthenticatedScriptIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/storyboard': typeof AuthenticatedStoryboardIndexRoute
  '/team': typeof AuthenticatedTeamIndexRoute
  '/projects/$id/assets': typeof AuthenticatedProjectsIdAssetsRouteRoute
  '/projects/$id/script': typeof AuthenticatedProjectsIdScriptRoute
  '/projects/$id/team': typeof AuthenticatedProjectsIdTeamRoute
  '/projects/$id': typeof AuthenticatedProjectsIdIndexRoute
  '/projects/$id/storyboard': typeof AuthenticatedProjectsIdStoryboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/assets': typeof AuthenticatedAssetsRouteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/storyboard-list': typeof AuthenticatedStoryboardListRoute
  '/_authenticated/storyboard-list-simple': typeof AuthenticatedStoryboardListSimpleRoute
  '/_authenticated/team': typeof AuthenticatedTeamRouteWithChildren
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/director/$director': typeof AuthenticatedDirectorDirectorRouteRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/api': typeof AuthenticatedSettingsApiRoute
  '/_authenticated/settings/api-docs': typeof AuthenticatedSettingsApiDocsRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/system/tasks': typeof AuthenticatedSystemTasksRoute
  '/_authenticated/character/': typeof AuthenticatedCharacterIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/script/': typeof AuthenticatedScriptIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/storyboard/': typeof AuthenticatedStoryboardIndexRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
  '/_authenticated/projects/$id/assets': typeof AuthenticatedProjectsIdAssetsRouteRoute
  '/_authenticated/projects/$id/script': typeof AuthenticatedProjectsIdScriptRoute
  '/_authenticated/projects/$id/team': typeof AuthenticatedProjectsIdTeamRoute
  '/_authenticated/projects/$id/': typeof AuthenticatedProjectsIdIndexRoute
  '/_authenticated/projects/$id/storyboard/': typeof AuthenticatedProjectsIdStoryboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/assets'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/storyboard-list'
    | '/storyboard-list-simple'
    | '/team'
    | '/test'
    | '/'
    | '/director/$director'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/api'
    | '/settings/api-docs'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/users'
    | '/system/tasks'
    | '/character'
    | '/help-center'
    | '/projects'
    | '/script'
    | '/settings/'
    | '/storyboard'
    | '/team/'
    | '/projects/$id/assets'
    | '/projects/$id/script'
    | '/projects/$id/team'
    | '/projects/$id'
    | '/projects/$id/storyboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assets'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/storyboard-list'
    | '/storyboard-list-simple'
    | '/test'
    | '/'
    | '/director/$director'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/api'
    | '/settings/api-docs'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/users'
    | '/system/tasks'
    | '/character'
    | '/help-center'
    | '/projects'
    | '/script'
    | '/settings'
    | '/storyboard'
    | '/team'
    | '/projects/$id/assets'
    | '/projects/$id/script'
    | '/projects/$id/team'
    | '/projects/$id'
    | '/projects/$id/storyboard'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/assets'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/storyboard-list'
    | '/_authenticated/storyboard-list-simple'
    | '/_authenticated/team'
    | '/_authenticated/test'
    | '/_authenticated/'
    | '/_authenticated/director/$director'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/api'
    | '/_authenticated/settings/api-docs'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/users'
    | '/_authenticated/system/tasks'
    | '/_authenticated/character/'
    | '/_authenticated/help-center/'
    | '/_authenticated/projects/'
    | '/_authenticated/script/'
    | '/_authenticated/settings/'
    | '/_authenticated/storyboard/'
    | '/_authenticated/team/'
    | '/_authenticated/projects/$id/assets'
    | '/_authenticated/projects/$id/script'
    | '/_authenticated/projects/$id/team'
    | '/_authenticated/projects/$id/'
    | '/_authenticated/projects/$id/storyboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storyboard-list-simple': {
      id: '/_authenticated/storyboard-list-simple'
      path: '/storyboard-list-simple'
      fullPath: '/storyboard-list-simple'
      preLoaderRoute: typeof AuthenticatedStoryboardListSimpleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storyboard-list': {
      id: '/_authenticated/storyboard-list'
      path: '/storyboard-list'
      fullPath: '/storyboard-list'
      preLoaderRoute: typeof AuthenticatedStoryboardListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedTeamRoute
    }
    '/_authenticated/storyboard/': {
      id: '/_authenticated/storyboard/'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof AuthenticatedStoryboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/script/': {
      id: '/_authenticated/script/'
      path: '/script'
      fullPath: '/script'
      preLoaderRoute: typeof AuthenticatedScriptIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/character/': {
      id: '/_authenticated/character/'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof AuthenticatedCharacterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/tasks': {
      id: '/_authenticated/system/tasks'
      path: '/system/tasks'
      fullPath: '/system/tasks'
      preLoaderRoute: typeof AuthenticatedSystemTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/api-docs': {
      id: '/_authenticated/settings/api-docs'
      path: '/api-docs'
      fullPath: '/settings/api-docs'
      preLoaderRoute: typeof AuthenticatedSettingsApiDocsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/api': {
      id: '/_authenticated/settings/api'
      path: '/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof AuthenticatedSettingsApiRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/director/$director': {
      id: '/_authenticated/director/$director'
      path: '/director/$director'
      fullPath: '/director/$director'
      preLoaderRoute: typeof AuthenticatedDirectorDirectorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/': {
      id: '/_authenticated/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/team': {
      id: '/_authenticated/projects/$id/team'
      path: '/projects/$id/team'
      fullPath: '/projects/$id/team'
      preLoaderRoute: typeof AuthenticatedProjectsIdTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/script': {
      id: '/_authenticated/projects/$id/script'
      path: '/projects/$id/script'
      fullPath: '/projects/$id/script'
      preLoaderRoute: typeof AuthenticatedProjectsIdScriptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/assets': {
      id: '/_authenticated/projects/$id/assets'
      path: '/projects/$id/assets'
      fullPath: '/projects/$id/assets'
      preLoaderRoute: typeof AuthenticatedProjectsIdAssetsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$id/storyboard/': {
      id: '/_authenticated/projects/$id/storyboard/'
      path: '/projects/$id/storyboard'
      fullPath: '/projects/$id/storyboard'
      preLoaderRoute: typeof AuthenticatedProjectsIdStoryboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsApiRoute: typeof AuthenticatedSettingsApiRoute
  AuthenticatedSettingsApiDocsRoute: typeof AuthenticatedSettingsApiDocsRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsApiRoute: AuthenticatedSettingsApiRoute,
    AuthenticatedSettingsApiDocsRoute: AuthenticatedSettingsApiDocsRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedTeamRouteChildren {
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
}

const AuthenticatedTeamRouteChildren: AuthenticatedTeamRouteChildren = {
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
}

const AuthenticatedTeamRouteWithChildren =
  AuthenticatedTeamRoute._addFileChildren(AuthenticatedTeamRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssetsRouteRoute: typeof AuthenticatedAssetsRouteRoute
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedStoryboardListRoute: typeof AuthenticatedStoryboardListRoute
  AuthenticatedStoryboardListSimpleRoute: typeof AuthenticatedStoryboardListSimpleRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRouteWithChildren
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDirectorDirectorRouteRoute: typeof AuthenticatedDirectorDirectorRouteRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedSystemTasksRoute: typeof AuthenticatedSystemTasksRoute
  AuthenticatedCharacterIndexRoute: typeof AuthenticatedCharacterIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedScriptIndexRoute: typeof AuthenticatedScriptIndexRoute
  AuthenticatedStoryboardIndexRoute: typeof AuthenticatedStoryboardIndexRoute
  AuthenticatedProjectsIdAssetsRouteRoute: typeof AuthenticatedProjectsIdAssetsRouteRoute
  AuthenticatedProjectsIdScriptRoute: typeof AuthenticatedProjectsIdScriptRoute
  AuthenticatedProjectsIdTeamRoute: typeof AuthenticatedProjectsIdTeamRoute
  AuthenticatedProjectsIdIndexRoute: typeof AuthenticatedProjectsIdIndexRoute
  AuthenticatedProjectsIdStoryboardIndexRoute: typeof AuthenticatedProjectsIdStoryboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssetsRouteRoute: AuthenticatedAssetsRouteRoute,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedStoryboardListRoute: AuthenticatedStoryboardListRoute,
  AuthenticatedStoryboardListSimpleRoute:
    AuthenticatedStoryboardListSimpleRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRouteWithChildren,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDirectorDirectorRouteRoute:
    AuthenticatedDirectorDirectorRouteRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedSystemTasksRoute: AuthenticatedSystemTasksRoute,
  AuthenticatedCharacterIndexRoute: AuthenticatedCharacterIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedScriptIndexRoute: AuthenticatedScriptIndexRoute,
  AuthenticatedStoryboardIndexRoute: AuthenticatedStoryboardIndexRoute,
  AuthenticatedProjectsIdAssetsRouteRoute:
    AuthenticatedProjectsIdAssetsRouteRoute,
  AuthenticatedProjectsIdScriptRoute: AuthenticatedProjectsIdScriptRoute,
  AuthenticatedProjectsIdTeamRoute: AuthenticatedProjectsIdTeamRoute,
  AuthenticatedProjectsIdIndexRoute: AuthenticatedProjectsIdIndexRoute,
  AuthenticatedProjectsIdStoryboardIndexRoute:
    AuthenticatedProjectsIdStoryboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
